spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/app-db
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 0